name: Test
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: get libs
        run: sudo apt-get update && sudo apt-get install -y imagemagick sox exiftool


      - name: Build tool
        run: make build

      - name: Create test files
        run: |
          mkdir test_src
          convert -size 100x100 xc:black test_src/picture.png
          sox -n -r 44100 -b 16 test_src/audio.wav synth 5 sine 440
          echo -n -e '\x52\x49\x46\x46' > test_src/audio_a.wav
          echo "hello" > test_src/file1.txt

      - name: Testing
        run: |
          echo "sync run testing"
          ./organizer --src test_src --dst test_dst
          echo "async run testing"
          ./organizer --src test_src --dst test_dst_async --async true
      - name: Check output
        run: |
          chmod +x ./cmpDirs.sh
          sudo ./cmpDirs.sh test_src test_dst
          sudo ./cmpDirs.sh test_src test_dst_async
